# -*- coding: utf-8 -*-
"""conversion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/nityambhargava/46c5ad3130ef419f08e3135edfb5d226/conversion.ipynb
"""

import pickle
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Load the model
with open('sentiment_model.pkl', 'rb') as file:
    model = pickle.load(file)

# Load the tokenizer
with open('tokenizer.pkl', 'rb') as file:
    tokenizer = pickle.load(file)

def predict_sentiment(review):
    # Tokenize and pad the review
    sequence = tokenizer.texts_to_sequences([review])
    padded_sequence = pad_sequences(sequence, maxlen=200)
    prediction = model.predict(padded_sequence)
    sentiment = "Positive" if prediction[0][0] > 0.5 else "Negative"
    return sentiment

new_review = "This movie was amazing. Fell in love with the storyline!"
sentiment = predict_sentiment(new_review)
print(f"The Sentiment of the review is: {sentiment}")

new_review = "This movie was boring!"
sentiment = predict_sentiment(new_review)
print(f"The Sentiment of the review is: {sentiment}")